<a href="https://colab.research.google.com/github/Anisha31415/dsml/blob/main/Day27.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
arr=np.array([
    [1,2,2],
    [5,6,7]
])

In [3]:
arr.shape

(2, 3)

In [4]:
arr.ndim # rank

2

In [13]:
arr.dtype

dtype('int64')

In [11]:
arr=np.array(["apple","banana", "cherryhgbjknkknkjnnn"]) #U: Unicode string data type.
arr.dtype

dtype('<U20')

In [22]:
#array reshaping
arr=np.array([
    [1,2,2],
    [5,6,7]
  ])


In [18]:
#2*3= 6 (1,6), (6,1),
reshaped_2d=arr.reshape(3,2)
reshaped_2d

array([[1, 2],
       [2, 5],
       [6, 7]])

In [34]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
reshaped_2d=arr.reshape((2,6))#reshape take value in tuple
reshaped_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [37]:
reshaped_2d.shape

(2, 6)

In [40]:
flattened=reshaped_2d.flatten()
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
raveled=reshaped_2d.ravel()
raveled

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
#flatten()=always creates a new copy
#ravel()=modifies the original array =but not creates new copy.

In [44]:
#array reshaping
arr=np.array([
    [1,2,2],
    [5,6,7]
  ])

In [46]:
arr.shape

(2, 3)

In [48]:
#transpose

transpose=arr.T
transpose


array([[1, 5],
       [2, 6],
       [2, 7]])

In [49]:
transpose.shape

(3, 2)

In [ ]:
#numpy array operation
import numpy as np

In [ ]:
arr.shape

In [56]:
#indexing and slicing
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:7])



[3 4 5 6 7]


In [57]:
print(arr[2])

3


In [ ]:
arr.shape

In [72]:
#indexing and slicing
arr=np.array([
    [1,2,3,4],
    [3,4,5,6],
    [4,5,6,7],
    ])

In [53]:
arr.shape

(3, 4)

In [54]:
#arr(row_start:row_end, col_start:col_end)

In [60]:
print(arr[0,2])

3


In [61]:
print(arr[2,2])#col_start:col_end

6


In [76]:
#sub matrix
print(arr[1:4, 1:4])

[[4 5 6]
 [5 6 7]]


In [65]:
#row only
print(arr[:2])


[[1 2 3 4]
 [3 4 5 6]]


In [ ]:
arr.shape

In [68]:
print(arr[:, :2])#first two column

[[1 2]
 [3 4]
 [4 5]]


In [70]:
print(arr[: :])#to print all

[[1 2 3 4]
 [3 4 5 6]
 [4 5 6 7]]


In [ ]:
#sort by row
print(np.sort(arr,axis=1))

In [77]:
#reverse rows
print(arr[::-1])

[[4 5 6 7]
 [3 4 5 6]
 [1 2 3 4]]


In [78]:
#reverse column
print(arr[:,::-1])

[[4 3 2 1]
 [6 5 4 3]
 [7 6 5 4]]


In [ ]:
#sort by row
print(np.sort(arr,axis=1))

In [79]:
#sorting,
unsorted=np.array([2,3,4,5,6,7,8,9])
print(np.sort(unsorted))

[2 3 4 5 6 7 8 9]


In [80]:

arr_2d_unsorted=np.array([
    [3,1],
    [1,2],
    [3,2]
])

In [81]:
print(np.sort(arr_2d_unsorted, axis=1))#sort by row

[[1 3]
 [1 2]
 [2 3]]


In [82]:
#sort by column
print(np.sort(arr_2d_unsorted, axis=0))

[[1 1]
 [3 2]
 [3 2]]


In [ ]:
#filter
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even=numbers[numbers%2==0]
print(even)

[ 2  4  6  8 10]


In [ ]:
#filter with mask
mask=numbers>5
print(numbers[mask])

[ 6  7  8  9 10]


In [ ]:
numbers[numbers>5]=123
print(numbers)

[  1   2   3   4   5 123 123 123 123 123]


In [ ]:
#np.where
where_result=np.where(numbers==5)
# get index position where the number 5 is

print(where_result)# gives index position of 5
print("number where",numbers[where_result])

(array([4]),)
number where [5]


In [ ]:
import numpy as np
numbers=np.array([2,8,4,10,5,7])
result=np.where(numbers>5)
print(result)


(array([1, 3, 5]),)


In [ ]:
conditional_array=np.where(numbers>5,numbers *4, numbers)
conditional_array

array([ 2, 32,  4, 40,  5, 28])

In [84]:
#adding data
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
add=arr1+arr2
add


array([5, 7, 9])

In [86]:
combine=np.concatenate((arr1,arr2))
combine

array([1, 2, 3, 4, 5, 6])

In [87]:
combine.shape

(6,)

In [88]:
arr1.shape==arr2.shape #check matrix compatibility

True

In [83]:
#row
original=np.array([[1,2],
      [3,4]
])

new_row=np.array([[5,6]])

added_row=np.vstack((original,new_row))#vertical stack
added_row

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#column add
original=np.array([[1,2],
      [3,4]
])

new_col=np.array([[5],[6]])
added_col=np.hstack((original,new_col))#horizontal stack
added_col

array([[1, 2, 5],
       [3, 4, 6]])