<a href="https://colab.research.google.com/github/Anisha31415/dsml/blob/main/Day26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#1D numpy
arr_id =np.array([1,2,3,4,5])
print(arr_id)

[1 2 3 4 5]


In [ ]:
#1D numpy
arr_id =np.array([1,2,3,4,5.5])
print(arr_id)

[1.  2.  3.  4.  5.5]


In [ ]:
#2D numpy
arr_2id =np.array([[1,2,3,4,5], [3,4,5,6,7]])
print(arr_2id)

[[1 2 3 4 5]
 [3 4 5 6 7]]


In [ ]:
#2D numpy
arr_2id =np.array([[1,2,3,4,5], [3,4,5,6,7]])
print(arr_2id)

[[1 2 3 4 5]
 [3 4 5 6 7]]


In [ ]:
#3D numpy
arr_3id =np.array([[[1,2,3,4,5], [3,4,5,6,7], [2,4,5,6,7], [3,4,5,6,7]]])
print(arr_3id)

[[[1 2 3 4 5]
  [3 4 5 6 7]
  [2 4 5 6 7]
  [3 4 5 6 7]]]


In [ ]:
arr_3id.shape


(1, 4, 5)

In [ ]:
#list vs numpy
#list
import time

start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n list operation time:",time.time()-start)


 list operation time: 0.03937506675720215


In [ ]:
#numpy
start=time.time()
np_array=np.arange(1000000)*2
print("\n Numpy operation time:",time.time()-start)


 Numpy operation time: 0.006427764892578125


In [ ]:
py_list=[1,2,3]
print("python list multiplication", py_list*3)

python list multiplication [1, 2, 3, 1, 2, 3, 1, 2, 3]


In [ ]:
my_array=np.array([1,2,3])#element wise multiplication

print("Numpy array multiplication", my_array*3) #3 is called scalar, we can perform vector multiplication

Numpy array multiplication [3 6 9]


In [ ]:
# Rank 0 (scalar)
a=np.array(10)
a.ndim

0

In [ ]:
# Rank 1(scalar)
a=np.array([1,2,3])
a.ndim

1

In [ ]:
# Rank 1(vector)
a=np.array([[1,2,3],[5,6,7]])
a.ndim

2

In [ ]:
a.shape

(2, 3)

In [ ]:
#class work
#create 5*5 matrix
a=np.array([
    [1,2,3,4,5],
    [5,6,7,5,4],
    [3,4,5,6,7],
    [5,2,1,4,6],
    [3,2,6,7,8]
  ])
a.ndim

2

In [ ]:
print(a.shape)
print(a)

(5, 5)
[[1 2 3 4 5]
 [5 6 7 5 4]
 [3 4 5 6 7]
 [5 2 1 4 6]
 [3 2 6 7 8]]


In [ ]:
# Calculate matrix rank also called no.of dimensions
rank = np.linalg.matrix_rank(a)
print("Matrix Rank:", rank)  # Output: 2 (Row 2 is a multiple of Row 1)


Matrix Rank: [[[5]]]


In [ ]:
zeros=np.zeros((5,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
ones=np.ones((5,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
ones=np.ones((5,5),dtype="int")
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
ones=np.ones((5,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a=np.array([
   [1,2,3],
   [4,5,6],
   [7,8,9]
])
print(a.sum(axis=0))#column wise sum
print(a.sum(axis=1))#row wise sum

[12 15 18]
[ 6 15 24]


In [ ]:
#random
random=np.random.random((3,3))
print(random)

[[0.84260268 0.44824076 0.87112274]
 [0.29543444 0.54508051 0.62034911]
 [0.2523801  0.25067089 0.4870962 ]]


In [ ]:
#full
full= np.full((3,3),5)
print(full)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
#linespace()-create evenly spaced value
arr= np.linspace(0,100,20)
arr

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [ ]:
#diag()-create diagonal matrix
arr=np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#eye=create 1 on diagonal
arr=np.eye(3,4)
arr


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#identity()/creates identity matrix(always square matrix)
arr=np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#create array of random numbers
arr=np.random.rand(2,3)
arr

array([[0.40003655, 0.05245113, 0.34255992],
       [0.25907271, 0.71040717, 0.65987999]])

In [ ]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [ ]:
arr=np.arange(3,8)#3 start and stop
arr

array([3, 4, 5, 6, 7])

In [ ]:
import numpy as np

In [ ]:
arr=np.random.rand(1,2,3,4)
print(arr)

[[[[0.56195033 0.45079081 0.95834655 0.45122881]
   [0.87593274 0.54286087 0.74246356 0.04355817]
   [0.35355974 0.78992942 0.05323605 0.57049123]]

  [[0.87350156 0.06837386 0.65452168 0.0804031 ]
   [0.68076404 0.16038081 0.45116878 0.87848854]
   [0.7536853  0.73686291 0.97313079 0.73853598]]]]


In [ ]:
arr.shape

(1, 2, 3, 4)

In [ ]:
arr_ad=np.array([[2,3,9], [1,4,2]])
print(arr_ad)
arr_ad.ndim

[[2 3 9]
 [1 4 2]]


2