<a href="https://colab.research.google.com/github/Anisha31415/dsml/blob/main/Day28.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy Numerical Python

In [44]:
#Element_wise Matrix operations
import numpy as np
matrix_1=np.array([
    [1,2],
    [3,4]
     ])
matrix_1

array([[1, 2],
       [3, 4]])

In [19]:
matrix_2=np.array([
    [4,6],
    [7,8]

])
matrix_2

array([[4, 6],
       [7, 8]])

In [6]:
result=matrix_1 + matrix_2 #element wise addition
result

array([[ 5,  8],
       [10, 12]])

In [8]:
matrix_sub=matrix_1- matrix_2 #element wise subtraction
matrix_sub

array([[-3, -4],
       [-4, -4]])

In [9]:
#matrix multiplication size
result_mux=matrix_1* matrix_2 #wrong concept
result_mux

array([[ 4, 12],
       [21, 32]])

In [10]:
result_mux = matrix_1 @ matrix_2  #right way to multiply
result_mux

array([[18, 22],
       [40, 50]])

In [12]:
result_mux=np.matmul(matrix_1, matrix_2) #alternative way
result_mux

array([[18, 22],
       [40, 50]])

In [15]:
#matrix division not important
result_div=matrix_1/matrix_2
result_div


array([[0.25      , 0.33333333],
       [0.42857143, 0.5       ]])

In [16]:
#elements wise operations with scalars
print(matrix_1)
print("/////////")
scalar=2
result_add=matrix_1+scalar
print(result_add)

[[1 2]
 [3 4]]
/////////
[[3 4]
 [5 6]]


In [22]:
print(matrix_1)
print("/////////")
scalar=2
result_mux=matrix_1 *scalar
print(result_mux)

[[1 2]
 [3 4]]
/////////
[[2 4]
 [6 8]]


In [23]:
#broadcasting  -allows  2D array to add with 1D array.
matrix_3 = np.array([
    [1,2],
    [3,4]
])
array_1 = np.array([5,6])#added to rows
result = matrix_3 + array_1
result

array([[ 6,  8],
       [ 8, 10]])

In [ ]:
#Determinants - use for matrix conversion and inverse

In [30]:
#computing the determinant
#we can calculate  the determinant of a matrix using linalg.det() function
A=np.array([
    [1,2],
    [3,4]
])
det=np.linalg.det(A)
print(det)

-2.0000000000000004


In [31]:
#inverse
#We can calulate the inverse of a matrix using the linalg.inv()function
inv_A=np.linalg.inv(A)
print(inv_A)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#A* A-1=I

In [32]:
print(A@inv_A)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [35]:
a= np.array([
    [2,1],
    [1,3]
])
b=np.array([5,6])
X=np.linalg.solve(a,b)
X

array([1.8, 1.4])

In [37]:
X=X*1.8
X

array([5.832, 4.536])

In [ ]:
#class task
#x+y+z=6
#2x+5y+z=-4
#2x+3y+8z=5


In [50]:
X = np.array([
    [1,1],
    [2,1],
    [3,1]
])

y = np.array([2,3,5])

beta=np.linalg.inv(X.T @ X) @ X.T @ y

In [51]:
print("slope(m)",beta[0])

slope(m) 1.499999999999999


In [52]:
print("Intercept(c):", beta[1])

Intercept(c): 0.3333333333333348
